apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "gmsa-win-demo"
  name: gmsa-win-demo
  namespace: simpleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "gmsa-win-demo"
  template:
    metadata:
      labels:
        app: "gmsa-win-demo"
    spec:
      securityContext:
        windowsOptions:
           gmsaCredentialSpecName: < GMSA Credential Spec Name >
      containers:
      - name: iis
        image: < Registry Name >.azurecr.io/windows/servercore/iis:windowsservercore-ltsc2019
        imagePullPolicy: IfNotPresent
        command:
          - powershell
        volumeMounts:
           - name: gmsa-win-demo
             mountPath: /gmsa-demo
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
      volumes:
        - name: gmsa-win-demo 
          configMap:
             defaultMode: 420
             name: gmsa-win-demo
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - < Windows Nodepool Name >
---
apiVersion: v1
kind: Service
metadata:
  name: gmsa-win-demo
  namespace: simpleapp
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: gmsa-win-demo
  ports:
  - protocol: TCP
    port: 80