apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gmsa
  namespace: simpleapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gmsa-spec-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: simpleapp